### PR TITLE
md: fix APU port in

### LINKED ISSUE #286: [MD] Thunder Force IV (Europe) Sounds worse compared to US version
The US version of this game seems to sound just fine, but the sound quality goes downhill as soon as I try the European version, tested it out in Blastem and it sounds fine there.  I also noticed that the sound quality immediately gets better as soon as you reset it once.

Tested on Version 125

### PR DESCRIPTION
**Pull request by rasky**
It's technically unused, but it must return 0xFF. Looks like some
game erroneously read it anyway.

Fixes #286

### CODE REVIEW

File: ares/md/apu/bus.cpp [hunk 1]
```diff
@@ -89,7 +89,7 @@ auto APU::writeExternal(n24 address, n8 data) -> void {
 
 auto APU::in(n16 address) -> n8 {
   //unused on Mega Drive
-  return 0x00;
+  return 0xFF;
```
Comment (LukeUsher) [inline ares/md/apu/bus.cpp]: Minor nitpick: it is code convention in ares to use lower case for constants like this

**Review by LukeUsher — CHANGES_REQUESTED** [review]

File: ares/md/apu/bus.cpp (hunk 1 above)
Comment (rasky) [reply ares/md/apu/bus.cpp]: fixed
